---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
 