---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "yes1name"
  namespace: "default"
  labels:
    app: "sentiapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "sentiapp"
  type: "LoadBalancer"
  loadBalancerIP: ""
